### PR TITLE
added basic download script

### PR DESCRIPTION
**Pull request by Goten87**
its ferry basic and not yet tested

### CODE REVIEW

**Comment by mide** [comment]
I'm not sure this is something that _most_ people need to do. Why would you ever downgrade your server? I feel like a mistaken call to this script could cause more pain than it's worth.

**Comment by mide** [comment]
Maybe if it had an `if` statement comparing the current version. Something like the following is an idea.

```
if (curVer > reqestedVer){
    if (flags == "-f"){
         // download older version
    }else{
        // don't download anything
    }
}else{
    // download newer version
}
```

**Comment by Goten87** [comment]
yeah oke but where do u want to get the curVer from then
as far as i know its not posebol to include websites to thiss to read data
like somthing from minecraft.net for the version

**Comment by mide** [comment]
I'm saying the currently installed version, not the current version of Minecraft. I don't think this script will be beneficial to anyone, would you use it? And if so, how often?

Do you feel that making this script could cause accidental downgrades? Is that risk worth the convince of something you only do once every six months or so anyway (or however often)?

**Comment by mide** [comment]
Also, I'm just thinking, since your current script is interactive, what would happen if they put in a _bad_ version number? Such as 6423?

**Pull request closed without merging**
