### PR TITLE
My look on the scripts now

### PR DESCRIPTION
**Pull request by Goten87**
Added admin.sh
added config.cfg (testing it)
added mc-restart.sh

### CODE REVIEW

**Comment by mide** [comment]
Alright, I've got a couple of questions before I merge in the changes. 
1. Why doesn't restart just contain calls to `mc-start.sh` and `mc-stop.sh`? 
2. I like the idea of the general config file. I'd like to clean it up before accepting it. 
3. The administration menu is a neat idea. I'll need to run it before being able comment further, but it looks like it could be a repetitive interface, always telling you the options. Maybe  `elif [ "${option}" = "help" ]; then` should show help? How are you dealing with capitalized input? (In other words, is backup the same as Backup or BackUp? 
4. Try to remove all existence of your setup (make default config values as generic as possible)

Otherwise, you've got some good ideas. Make those small changes (if you need help let me know) and I'll gladly merge it in.

**Comment by Goten87** [comment]
i mean the restart

**Comment by Goten87** [comment]
and what do u mean with help becose all the info is alrdy in there what u need to know

**Comment by Goten87** [comment]
hehe hope u like my work so far m8 xD

**Comment by mide** [comment]
What have you done with the backup script? Why two scripts? And why does it need to know how often cron runs it? If it runs every hour, it shouldn't matter inside the application, just in cron. Do you know what I'm saying?

**Comment by Goten87** [comment]
the cron time was more for the text in the backup-cron file like i will show u here:
`screen -p 0 -S minecraft -X eval "stuff \"say $backupTime hour has passed, time for a backup..\"\015""`

but i will delete the cron file and keep only the backup normal in the job will make it for my self then becose my friends always forget the time so its nice to let them know there is a other hour pass

can u make then mc-temp-creative.sh is the same as time and stuff
so we can do: `./mc-temp-creative.sh 10`
other then a config file for it

or is this already like this
if so why is there a config in the file with `min=10`

**Comment by mide** [comment]
I can make the `./mc-temp-creative.sh` support arguments. I will do that now, it is a good idea. As far as the rest of this pull request, I need to review your latest revisions. I will comment back soon.

**Comment by Goten87** [comment]
yeah i'm still working on it will make the `DATE=$(date +%d.%m.%Y-%T)` also in the config file with the install script
so people can make there own timestamp setup

ok not working for the timestamp its printing the date out and not what i want :P so i added it back now

**Pull request closed without merging**
